"""balance column added to bankaccount table

Revision ID: 1ddb2fbe7c6f
Revises: 4c6a733f6c23
Create Date: 2023-08-18 21:08:51.670606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ddb2fbe7c6f'
down_revision = '4c6a733f6c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccount', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
