"""nullable option removed for picture column

Revision ID: 415e87646108
Revises: 1fb2250280e4
Create Date: 2023-08-17 21:17:52.569518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '415e87646108'
down_revision = '1fb2250280e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('picture',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###
