"""balance column added to bankaccount table

Revision ID: d269ffb5018e
Revises: 58e06e1c083d
Create Date: 2023-08-18 21:10:41.454124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd269ffb5018e'
down_revision = '58e06e1c083d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccount', schema=None) as batch_op:
        batch_op.add_column(sa.Column('balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bankaccount', schema=None) as batch_op:
        batch_op.drop_column('balance')

    # ### end Alembic commands ###
